### ISSUE TITLE
tj/commander.js

### ISSUE THREAD

**Issue by zhiyelee** [visionmedia/readme#1]
hi tj, http://visionmedia.github.io/commander.js/ can not work.

Besides, the content of that site are a little old, how can we make it up to date. I am one of the maintainer of [tj/commander.js](https://github.com/tj/commander.js)

**Comment by zhiyelee** [comment]
And one more thing, we can't modify the the description of the repo to change the changed URL.  Maybe  one of we maintainers can be set as a owner if possible.

**Comment by zhiyelee** [comment]
ping @tj

**Comment by tj** [comment]
yeah it's super outdated, it would be nicer to just ditch it and use the readme

**Comment by tj** [comment]
removed it from the GH form since it's in the readme

**Comment by zhiyelee** [comment]
Ok, I will rewrite the README later.
